/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/ui/BaseHeader.vue')['default']
    ThemeToggle: typeof import('./src/components/ui/ThemeToggle.vue')['default']
  }
}
